services:
  - type: web
    name: dash-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python dashboard.py
    envVars:
      - key: PORT
        value: 10000
